# Generated by Django 4.1.3 on 2022-11-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro', '0003_category_cuisine_menu_item_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_item',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='menu_item',
            old_name='cuisines',
            new_name='cuisine',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='title',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
